### ISSUE TITLE
startEchoTest returns -8 and fails to echo back

### ISSUE THREAD

**Issue by ChrisMICDUP** [AgoraIO-Extensions/Agora-Flutter-SDK#1173]
I am attempting to implement a startEchoTest, but calling this returns -8 and does not function as expected. I am unable to find what this means (in the AgoraErrorCode documentation the code it skips from 7 to 9)

When I run this test, the application is already connected to a channel. The user is a Host. I create a token with a unique channel Id and a uid of 0xFFFFFFFF. I only wish to test Audio.

After speaking for over 2 seconds I expect to hear my voice repeated back.

What else should I try?

Example Code:

```
Future<void> _startEchoTest() async {
    Random random = new Random();
    int randomNumber = random.nextInt(100);
    String uniqueChannelId = '${widget.channelId}_$randomNumber';
    TokenResult? agoraTokenUid = await AgoraMicroService.getToken(uniqueChannelId, '0xFFFFFFFF', '1', null);

    widget.rtc.engine?.startEchoTest(
      EchoTestConfiguration(
        token: agoraTokenUid?.token,
        channelId: uniqueChannelId,
        enableVideo: false,
        enableAudio: true,
        intervalInSeconds: 2)
      );
  }
```

Log: 

```
flutter: XXXXX getToken /api/get/tokens/bigangein4hosts1687132959468_54?role=1&timeout=null&userAccount=0xFFFFFFFF
flutter: response = {"code":200,"rtc_token":"00613629663327f4d27bc13f073dc6f52b9IAC1kHzOGsuBSmWjHxAfpmFm03JZnGPFmUNt2VfuWIC7pUG2aBuHvm31IgAd3PEFdZabZAQAAQAVYZpkAgAVYZpkAwAVYZpkBAAVYZpk","rtm_token":"00613629663327f4d27bc13f073dc6f52b9IAAuxfUZJXAp7hxAd+ubIuJfth/9Hr9xuXiwJTn93AXJSVIs1sgAAAAAEAAKlDoEdZabZAEA6AMVYZpk","uid":1076467332}
flutter: response.statusCode = 200, phrase = OK
[info] [iris_rtc_engine_impl.cc:97] api name RtcEngine_startEchoTest3 params {"config":{"channelId":"bigangein4hosts1687132959468_54","enableAudio":true,"enableVideo":false,"intervalInSeconds":2,"token":"00613629663327f4d27bc13f073dc6f52b9IAC1kHzOGsuBSmWjHxAfpmFm03JZnGPFmUNt2VfuWIC7pUG2aBuHvm31IgAd3PEFdZabZAQAAQAVYZpkAgAVYZpkAwAVYZpkBAAVYZpk"}}
[info] [iris_rtc_engine_impl.cc:113] api name RtcEngine_startEchoTest3 ret 0 result {"result":-8}
[info] [iris_rtc_engine_impl.cc:97] api name RtcEngine_stopEchoTest params {}
[info] [iris_rtc_engine_impl.cc:113] api name RtcEngine_stopEchoTest ret 0 result {"result":-5}
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: AgoraRtcException(-5, null)
#0      RtcEngineImpl.stopEchoTest (package:agora_rtc_engine/src/binding/agora_rtc_engine_impl.dart:414:7)
<asynchronous suspension>
```

iPhone XS iOS 16.5
Agora Flutter SDK 6.2.0 / iOS 4.2.0

**Comment by littleGnAl** [comment]
Can you try this example to see if it works or not?
https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/example/lib/examples/advanced/precall_test/precall_test.dart

**Comment by ChrisMICDUP** [comment]
The PreCallTest isn't enabled for iOS or Android it seems

```
  if (kIsWeb || !(Platform.isAndroid || Platform.isIOS))
    {'name': 'PreCallTest', 'widget': const PreCallTest()},
```

Removing that check and running gives:

```
[info] [iris_rtc_device_manager_impl.cc:48] api name AudioDeviceManager_getRecordingDevice params {}
[error] [iris_rtc_device_manager_impl.cc:55] api name AudioDeviceManager_getRecordingDevice ret -1 result 
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: AgoraRtcException(-1, null)
#0      AudioDeviceManagerImpl.getRecordingDevice (package:agora_rtc_engine/src/binding/audio_device_manager_impl.dart:169:7)
<asynchronous suspension>
#1      _State._enumerateVideoDevices (package:agora_rtc_engine_example/examples/advanced/precall_test/precall_test.dart:156:34)
<asynchronous suspension>
#2      _State._initEngine (package:agora_rtc_engine_example/examples/advanced/precall_test/precall_test.dart:114:5)
<asynchronous suspension>
C++ got rtc.enable_xdump_upload notify: dirpath=/uw/config/global/rtc.enable_xdump_upload: val=5
```

I'll keep having a play, as there are some other examples I am interested in. A few Android only things (perms for instance) in code though.

**Comment by littleGnAl** [comment]
I'm sorry that the `PreCallTest` case only works on desktop at this time.

I think you can try to call the `startEchoTest ` before `joinChannel`.

**Comment by ChrisMICDUP** [comment]
I've got it working with a bit of hacking, but as you said it only works when the app has NOT already joined a channel. 

```
I/spdlog  ( 1503): [2023-06-30 14:12:29.972] [1503] [info] [iris_rtc_engine_impl.cc:97] api name RtcEngine_startEchoTest3 params {"config":{"channelId":"testEcho","intervalInSeconds":4,"token":"0****="}}
I/agora.io( 1503): (00000213): RtcEngine::startEchoTest(this:0xcd385c00, {"config":{"view":"0x0", "enableAudio":1, "enableVideo":1, "token":"0****=", "channelId":"testEcho", "intervalInSeconds":4}})
I/agora.io( 1503): (00000214):   RtcEngine::startEchoTest_(this:0xcd385c00, config[a/v: 1/1, cname:testEcho, view:0x0, token:0****=] interval:4)
E/agora.io( 1503): API call to start echo test: Already in channel(audio track published).
I/spdlog  ( 1503): [2023-06-30 14:12:29.974] [1503] [info] [iris_rtc_engine_impl.cc:113] api name RtcEngine_startEchoTest3 ret 0 result {"result":-8}
```

This seems to contradict the documentation at https://api-ref.agora.io/en/video-sdk/flutter/6.x/API/class_irtcengine.html#api_irtcengine_startechotest3 where it says:

> Attention:
> You can call this method either before or after joining a channel.

Let me know if you want to see what changes I needed to make to get the precall working on phones

**Comment by littleGnAl** [comment]
@ChrisMICDUP 
The doc is a little confusing for "after joining a channel", you can call it after joining a channel only the audio/video not be published, say that this should work
```dart
  await _engine.joinChannel(
    token: '<token>',
    channelId: 'channelId',
    uid: 0,
    options: ChannelMediaOptions(
      ...
      publishCameraTrack: false, // do not publish the video
      publishMicrophoneTrack: false, // do not publish the audio
    ),
  );

  // Then call `startEchoTest `
```

I had requested the doc team to update the doc.

**Comment by ChrisMICDUP** [comment]
Thanks @littleGnAl I have it working now. For any others dropping by this issue and for Agora docs, my use case is that I have already joined an Agora channel with video and audio enabled. I now wish to run the echoTest to confirm my audio is clear.

I am required to do the following: 1. Generate a new token with the uid of 0xFFFFFFFF (my token service requires a string), 2. disable video and audio, 3. run echo test, 4. stop echo test, 5. reenable video and audio. Note that others in the channel will hear your test

```
    TokenResult? agoraTokenUid = await AgoraMicroService.getToken(widget.channelId, 0xFFFFFFFF.toString(), '1', null);
    await widget.rtc.engine?.updateChannelMediaOptions(ChannelMediaOptions(publishMicrophoneTrack: false, publishCameraTrack: false));

    await widget.rtc.engine?.startEchoTest(
      EchoTestConfiguration(
        token: agoraTokenUid?.token,
        channelId: widget.channelId,
        intervalInSeconds: 4)
      );
```

**Comment by littleGnAl** [comment]
`updateChannelMediaOptions ` should work too, just keep in mind that do not publish the audio/video before `startEchoTest ` should be fine.
