### ISSUE TITLE
ArgumentError: Invalid argument(s): `6` is not one of the supported values: -1, 0, 1, 2, 3, 4, 5

### ISSUE THREAD

**Issue by lewooz** [AgoraIO-Extensions/Agora-Flutter-SDK#1207]
Argument error happens when native side returns network type with number '6' from method channel.

This is the error log:

`Traceback (most recent call last):
  File "package:json_annotation/src/enum_helpers.dart", line 37, in $enumDecodeNullable
  File "package:agora_rtc_engine/src/binding/event_handler_param_json.g.dart", line 1898, in _$RtcEngineEventHandlerOnNetworkTypeChangedJsonFromJson
  File "package:agora_rtc_engine/src/binding/event_handler_param_json.dart", line 2461, in new RtcEngineEventHandlerOnNetworkTypeChangedJson.fromJson
  File "package:agora_rtc_engine/src/binding/agora_rtc_engine_event_impl.dart", line 1495, in RtcEngineEventHandlerWrapper.handleEventInternal
  File "package:agora_rtc_engine/src/binding/agora_rtc_engine_event_impl.dart", line 1795, in RtcEngineEventHandlerWrapper.handleEvent
  File "package:iris_method_channel/src/iris_method_channel.dart", line 479, in IrisMethodChannel.initilize.<anonymous closure>
  File "dart:async/zone.dart", line 1414, in _rootRunUnary
  File "dart:async/zone.dart", line 1307, in _CustomZone.runUnary
  File "dart:async/zone.dart", line 1216, in _CustomZone.runUnaryGuarded
  File "dart:async/stream_impl.dart", line 339, in _BufferingStreamSubscription._sendData
  File "dart:async/stream_impl.dart", line 271, in _BufferingStreamSubscription._add
  File "dart:async/stream_controller.dart", line 774, in _SyncStreamControllerDispatch._sendData
  File "dart:async/stream_controller.dart", line 648, in _StreamController._add
  File "dart:async/stream_controller.dart", line 596, in _StreamController.add
  File "dart:isolate-patch/isolate_patch.dart", line 192, in _RawReceivePort._handleMessage
ArgumentError: Invalid argument(s): `6` is not one of the supported values: -1, 0, 1, 2, 3, 4, 5`

I made a #[pull request](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1205) to fix the issue.

**Comment by littleGnAl** [comment]
Fixed https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/pull/1205
