### ISSUE TITLE
app crashes on android 10 oppo, huawei when enable local audio 

### ISSUE THREAD

**Issue by Mo0Khaled** [AgoraIO-Extensions/Agora-Flutter-SDK#1356]
version : agora_rtc_engine: ^6.2.2

flutter version: Flutter 3.13.6 • channel stable
logs

```
E/AndroidRuntime(20628): FATAL EXCEPTION: main
E/AndroidRuntime(20628): Process: com.nagwa.classes, PID: 20628
E/AndroidRuntime(20628): java.lang.NullPointerException: Attempt to read from field 'android.view.WindowManager$LayoutParams android.view.ViewRootImpl.mWindowAttributes' on a null object reference
E/AndroidRuntime(20628): 	at android.view.inputmethod.InputMethodManager.startInputInner(InputMethodManager.java:1668)
E/AndroidRuntime(20628): 	at android.view.inputmethod.InputMethodManager.checkFocus(InputMethodManager.java:1909)
E/AndroidRuntime(20628): 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:4897)
E/AndroidRuntime(20628): 	at android.os.Handler.dispatchMessage(Handler.java:110)
E/AndroidRuntime(20628): 	at android.os.Looper.loop(Looper.java:219)
E/AndroidRuntime(20628): 	at android.app.ActivityThread.main(ActivityThread.java:8349)
E/AndroidRuntime(20628): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(20628): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
E/AndroidRuntime(20628): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1055)
I/spdlog  (20628): [2023-10-08 08:51:19.384] [20628] [info] [iris_rtc_engine_impl.cc:96] api name RtcEngine_muteLocalAudioStream params {"mute":true}
I/agora.io(20628): (00000119): RtcEngine::muteLocalAudioStream(this:0x752b152d00, {"mute":1})
```

**Comment by littleGnAl** [comment]
Can you please raise a new ticket to Agora support for this issue for further investigation, thanks.
