### ISSUE TITLE
[Web] Error with onAudioVolumeIndication event deserialization

### ISSUE THREAD

**Issue by dannnnthemannnn** [AgoraIO-Extensions/Agora-Flutter-SDK#1840]
### Version of the agora_rtc_engine

6.3.2

### Platforms affected

- [ ] Android
- [ ] iOS
- [ ] macOS
- [ ] Windows
- [X] Web

### Steps to reproduce

1. Turn on AudioVolumeIndication `await engine.enableAudioVolumeIndication(interval: 200, smooth: 3, reportVad: true);`
2. See that it fails due to deserialization issues

### Expected results

It sends volume indication events properly

### Actual results

It fails

### Code sample

<details open><summary>Code sample</summary>

```dart
await engine.enableAudioVolumeIndication(interval: 200, smooth: 3, reportVad: true);
```

</details>

### Screenshots or Video

<details open>
<summary>Screenshots / Video demonstration</summary>

N/A

</details>

### Logs

<details open><summary>Logs</summary>

```console
Error
    at Object.throw_ [as throw] (errors.dart:296:3)
    at Object._failedAsCheck (rti.dart:1388:3)
    at dart_rti.Rti.new._generalNullableAsCheckImplementation (rti.dart:1378:3)
    at Object._$36RtcEngineEventHandlerOnAudioVolumeIndicationJsonFromJson [as _$RtcEngineEventHandlerOnAudioVolumeIndicationJsonFromJson] (event_handler_param_json.g.dart:1446:45)
    at RtcEngineEventHandlerOnAudioVolumeIndicationJson.fromJson (event_handler_param_json.dart:1673:7)
    at agora_rtc_engine_event_impl.RtcEngineEventHandlerWrapper.new.handleEventInternal (agora_rtc_engine_event_impl.dart:153:62)
    at agora_rtc_engine_event_impl.RtcEngineEventHandlerWrapper.new.handleEvent (agora_rtc_engine_event_impl.dart:1914:9)
    at iris_method_channel.dart:64:20
    at [_onEventFromJS] (iris_method_channel_internal_web.dart:98:34)
    at Object._checkAndCall (operations.dart:426:37)
    at Object.dcall (operations.dart:431:39)
    at o.ret [as _eventHandler] (js_allow_interop_patch.dart:17:11)
    at o.onEvent (iris-web-rtc.js:2:892986)
    at iris-web-rtc.js:2:893907
    at Array.forEach (<anonymous>)
    at t.IrisEventHandlerManagerImpl.notifyEvent (iris-web-rtc.js:2:893892)
    at t.IRtcEngineEventHandler.notifyEvent (iris-web-rtc.js:2:932897)
    at t.IRtcEngineEventHandler.onAudioVolumeIndication_781482a (iris-web-rtc.js:2:953309)
    at iris-web-rtc.js:2:1139732
```

</details>

### Flutter Doctor output

<details open><summary>Doctor output</summary>

```console
[✓] Flutter (Channel stable, 3.22.2, on macOS 14.1.1 23B81 darwin-arm64, locale en-US)
[!] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[!] Xcode - develop for iOS and macOS (Xcode 15.4)
    ✗ CocoaPods not installed.
        CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on
        the Dart side.
        Without CocoaPods, plugins will not work on iOS or macOS.
        For more info, see https://flutter.dev/platform-plugins
      To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.
[✓] Chrome - develop for the web
[✓] Android Studio (version 2023.2)
[✓] VS Code (version 1.84.2)
[✓] VS Code (version 1.90.0-insider)

```

</details>

**Comment by dannnnthemannnn** [comment]
FYI this fixed it for me: https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/commit/6b0f2ae2e13d8cfc4341f91d6c325d3dd659d4dd#diff-d77ff0819e0ada930b5a8cac10a4d2851fa9243f0fa8b59a28ed16c76d4f16bb

**Comment by littleGnAl** [comment]
@dannnnthemannnn Thanks for your report, can you also share the log of this callback (there should be an event name and JSON data of this callback in the log), so we can check what we get from the JS side.

**Comment by dannnnthemannnn** [comment]
Hello @littleGnAl Where would I find those logs on web? I see for the other platforms the defualt log locations: 

```
Android: /storage/emulated/0/Android/data//files/agora-iris.log
iOS: App Sandbox/Library/caches/agora-iris.log
macOS: /Users//Library/Containers//Data/Library/Logs/agora-iris.log
Windows: C:\Users<user_name>\AppData\Local\Agora<process_name>\agora-iris.log
```

I dont see a log file at /Users//Library/Containers//Data/Library/Logs/agora-iris.log on my mac.

**Comment by littleGnAl** [comment]
On the web, this log only outputs to the console.

**Comment by dannnnthemannnn** [comment]
@littleGnAl Unfortunately it seems like the log is not outputting the raw JSON that is failing to parse or anything: 

```
iris-web-rtc.js:2 [4:03:10 PM:545][Iris log]:[callIrisApiAsync][result] RtcEngine_enableAudioVolumeIndication_39794a0 ret 0
iris-web-rtc.js:1 16:03:10:659 Agora-SDK [DEBUG]: [lock-P2PConnection-mutex-10] is not locked, current queue 0. From P2PConnection.connect
iris-web-rtc.js:1 16:03:10:660 Agora-SDK [DEBUG]: [lock-P2PChannel-mutex-9] is not locked, current queue 0. From P2PChannel.connect
iris-web-rtc.js:1 16:03:10:680 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onICEConnectionStateChange(checking)
iris-web-rtc.js:1 16:03:10:681 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onICETransportStateChange(checking)
iris-web-rtc.js:1 16:03:10:683 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onConnectionStateChange(connecting)
errors.dart:296 Uncaught Error
    at Object.throw_ [as throw] (errors.dart:296:3)
    at Object._failedAsCheck (rti.dart:1388:3)
    at dart_rti.Rti.new._generalNullableAsCheckImplementation (rti.dart:1378:3)
    at Object._$36RtcEngineEventHandlerOnAudioVolumeIndicationJsonFromJson [as _$RtcEngineEventHandlerOnAudioVolumeIndicationJsonFromJson] (event_handler_param_json.g.dart:1446:45)
    at RtcEngineEventHandlerOnAudioVolumeIndicationJson.fromJson (event_handler_param_json.dart:1673:7)
    at agora_rtc_engine_event_impl.RtcEngineEventHandlerWrapper.new.handleEventInternal (agora_rtc_engine_event_impl.dart:153:62)
    at agora_rtc_engine_event_impl.RtcEngineEventHandlerWrapper.new.handleEvent (agora_rtc_engine_event_impl.dart:1914:9)
    at iris_method_channel.dart:64:20
    at [_onEventFromJS] (iris_method_channel_internal_web.dart:98:34)
    at Object._checkAndCall (operations.dart:426:37)
    at Object.dcall (operations.dart:431:39)
    at o.ret [as _eventHandler] (js_allow_interop_patch.dart:17:11)
    at o.onEvent (iris-web-rtc.js:2:892986)
    at iris-web-rtc.js:2:893907
    at Array.forEach (<anonymous>)
    at t.IrisEventHandlerManagerImpl.notifyEvent (iris-web-rtc.js:2:893892)
    at t.IRtcEngineEventHandler.notifyEvent (iris-web-rtc.js:2:932897)
    at t.IRtcEngineEventHandler.onAudioVolumeIndication_781482a (iris-web-rtc.js:2:953309)
    at iris-web-rtc.js:2:1139732
iris-web-rtc.js:1 16:03:10:772 Agora-SDK [INFO]: [client-73ece] [pc-1] selectedcandidatepairchange: local {"candidateType":"prflx","protocol":"udp"}, remote {"candidateType":"host","protocol":"udp","address":"128.1.193.201","port":4710} )
iris-web-rtc.js:1 16:03:10:772 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onDTLSTransportStateChange(connecting)
iris-web-rtc.js:1 16:03:10:772 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onICEConnectionStateChange(connected)
iris-web-rtc.js:1 16:03:10:773 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onICETransportStateChange(connected)
iris-web-rtc.js:1 16:03:10:773 Agora-SDK [DEBUG]: [client-73ece] [pc-1] local candidate count 6
iris-web-rtc.js:1 16:03:10:859 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onDTLSTransportStateChange(connected)
iris-web-rtc.js:1 16:03:10:862 Agora-SDK [INFO]: [client-73ece] [p2pId: 1]: P2PConnection.onConnectionStateChange(connected)
errors.dart:296 Uncaught Error
    at Object.throw_ [as throw] (errors.dart:296:3)
    at Object._failedAsCheck (rti.dart:1388:3)
    at dart_rti.Rti.new._generalNullableAsCheckImplementation (rti.dart:1378:3)
    at Object._$36RtcEngineEventHandlerOnAudioVolumeIndicationJsonFromJson [as _$RtcEngineEventHandlerOnAudioVolumeIndicationJsonFromJson] (event_handler_param_json.g.dart:1446:45)
    at RtcEngineEventHandlerOnAudioVolumeIndicationJson.fromJson (event_handler_param_json.dart:1673:7)
    at agora_rtc_engine_event_impl.RtcEngineEventHandlerWrapper.new.handleEventInternal (agora_rtc_engine_event_impl.dart:153:62)
    at agora_rtc_engine_event_impl.RtcEngineEventHandlerWrapper.new.handleEvent (agora_rtc_engine_event_impl.dart:1914:9)
    at iris_method_channel.dart:64:20
    at [_onEventFromJS] (iris_method_channel_internal_web.dart:98:34)
    at Object._checkAndCall (operations.dart:426:37)
    at Object.dcall (operations.dart:431:39)
    at o.ret [as _eventHandler] (js_allow_interop_patch.dart:17:11)
    at o.onEvent (iris-web-rtc.js:2:892986)
    at iris-web-rtc.js:2:893907
    at Array.forEach (<anonymous>)
    at t.IrisEventHandlerManagerImpl.notifyEvent (iris-web-rtc.js:2:893892)
    at t.IRtcEngineEventHandler.notifyEvent (iris-web-rtc.js:2:932897)
    at t.IRtcEngineEventHandler.onAudioVolumeIndication_781482a (iris-web-rtc.js:2:953309)
```

**Comment by cbj0hns0n** [comment]
Hi @littleGnAl ! @dannnnthemannnn suggested a fix in a comment above that resolved this issue. I searched for the [contributing guide](https://github.com/AgoraIO-Extensions/Agora-Flutter-SDK/blob/main/CONTRIBUTING.md#contribute-your-code) for Web and didn't see it yet. What is the process like for merging the proposes changes above?
