### ISSUE TITLE
Questions related to Flutter Web

### ISSUE THREAD

**Issue by mrtordoide** [AgoraIO-Extensions/Agora-Flutter-SDK#402]
How to enable Tab Share Audio when screen sharing and how can I switch between camera and microphone interfaces from Flutter Web?

**Comment by LichKing-2234** [comment]
use device manager

**Comment by mrtordoide** [comment]
@LichKing-2234 , when using `_engine.deviceManager`, I get this error every time.

```
Error: PlatformException(error, Expected a value of type 'bool', but got one of type 'Null', null, null)
    at Object.throw_ [as throw] (http://localhost:61616/dart_sdk.js:5061:11)
    at StandardMethodCodec.decodeEnvelope (http://localhost:61616/packages/flutter/src/services/restoration.dart.lib.js:2286:19)
    at MethodChannel._invokeMethod (http://localhost:61616/packages/flutter/src/services/restoration.dart.lib.js:1528:47)
    at _invokeMethod.next (<anonymous>)
    at http://localhost:61616/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:61616/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:61616/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:61616/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:61616/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:61616/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:61616/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:61616/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:61616/dart_sdk.js:38784:13)
    at http://localhost:61616/dart_sdk.js:34519:9
```

**Comment by LichKing-2234** [comment]
@mrtordoide Fixed.

**Comment by mrtordoide** [comment]
@LichKing-2234 Thanks. I will check deviceManager soon but can you also please look into Tab Share Audio? Even if my chrome version is latest, Share Audio option is not available for me.

**Comment by LichKing-2234** [comment]
@mrtordoide Supported.

**Comment by mehrbat** [comment]
@mrtordoide 
@LichKing-2234 
I cannot find any good documentation on how to use screen sharing with Flutter web. Can you please point me to the right direction for this?

Really appreciate your help!

**Comment by LichKing-2234** [comment]
@mehrbat pls follow the example which named `screen_sharing.dart`

**Comment by Muhammad-Ullah** [comment]
This line await "_engine.joinChannel(config.token, channelId, null,config.uid);" gives this error
   
PlatformException(error, AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: flag: 4096, message: AgoraRTCError CAN_NOT_GET_GATEWAY_SERVER: dynamic use static key data:
{"retry":false,"csIp":"52.172.27.120"}, null, null)

**Comment by littleGnAl** [comment]
The web support for `agora_rtc_engine` 6.x has landed in the `main` branch, If you still face issues, please try the latest code in `main` branch to see if it works or not.
